mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info

external-controller: 0.0.0.0:9090
unified-delay: true
geodata-mode: true

profile:
  store-selected: false
  store-fake-ip: false
  persist: true

proxies:
  - name: "residential"
    type: {{ .ISPProtocol }}
    server: {{ .ISPServer }}
    port: {{ .ISPPort }}
    username: {{ .ISPUsername }}
    password: {{ .ISPPassword }}
    udp: true
    interface-name: "tun0"

proxy-groups:
  - name: "AUTO"
    type: select
    proxies:
      - residential

rules:
  - MATCH,AUTO