base:
  app:
    service_name: proxyhub
    local_ip: 0.0.0.0
    api_port: 9901
    admin_port: 8001
    run_mode: debug

  log:
    level: debug
    development: true
    log_path: logs

  mysql:
    write_db_host: 127.0.0.1
    write_db_port: 3306
    write_db_user: root
    write_db_password: 12345678
    write_db: proxy_hub
    table_prefix: tbl_
    max_idle_conns: 10
    max_open_conns: 1000
    logging: true
    log_level: info
    # 客户端连接的存活时间(分钟)，该值请小于当前环境MySQL wait_timeout的时间，避免服务端主动断开连接的风险
    conn_max_life_time: 0

custom_cfg:
  # 模拟器多久没有更新IP，单位小时
  interval_time: 1

cron_job:
  # 自动释放IP的执行周期
  release_ip: "*/1 * * * *"