basePath: /
definitions:
  common.Response:
    properties:
      Data: {}
      Message:
        type: string
      RetCode:
        $ref: '#/definitions/common.RetCode'
    type: object
  common.ResponseWithTotalCount:
    properties:
      Data: {}
      Message:
        type: string
      RetCode:
        $ref: '#/definitions/common.RetCode'
      TotalCount:
        type: integer
    type: object
  common.RetCode:
    enum:
    - 0
    - 4030
    - 100050
    - 6003
    - 6004
    - 6005
    - 6006
    - 6007
    - 6008
    - 6009
    - 6010
    - 6011
    - 6012
    - 6013
    - 6014
    - 6015
    type: integer
    x-enum-varnames:
    - SUCCESS
    - FORBIDDEN
    - ActionNotFound
    - FAILED
    - ErrorDatabaseRead
    - ErrorDatabaseWrite
    - ErrInvalidParams
    - ErrInvalidJSONParams
    - ErrorPrivilege
    - ErrorResourceNotExist
    - ErrorCallOtherSrv
    - ActionFailed
    - ErrGetList
    - ErrGetDetail
    - ErrDelete
    - ErrCreate
  models.ProxyGroups:
    properties:
      CreateTime:
        type: integer
      Creator:
        type: string
      Deleter:
        type: string
      Description:
        type: string
      Id:
        type: integer
      MaxOnline:
        type: integer
      Name:
        type: string
      UpdateTime:
        description: 更新时间
        type: integer
      Updater:
        type: string
    type: object
  proxy_group.CreateParams:
    properties:
      Description:
        description: 描述
        type: string
      MaxOnline:
        description: 该分组内的IP最大同时在线模拟器数
        type: integer
      Name:
        description: 组名
        type: string
    type: object
  proxy_group.DeleteParams:
    properties:
      ids:
        description: 待删除 ID 列表
        items:
          type: integer
        type: array
    required:
    - ids
    type: object
  types.BasicQuery:
    properties:
      Fields:
        description: 指定返回字段
        items:
          type: string
        type: array
      FuzzyField:
        additionalProperties:
          type: string
        description: 模糊查询字段
        type: object
      IdList:
        description: id数组
        items:
          type: integer
        type: array
      Keyword:
        description: 关键词(全局模糊搜索)
        type: string
      Limit:
        description: 分页条数
        type: integer
      Offset:
        description: 分页偏移量
        type: integer
      Order:
        description: 排序，支持desc和asc
        type: string
      OrderBy:
        description: 排序字段，默认按照创建时间降序
        type: string
      Query:
        description: 自定义查询语句；使用RSQL语法，具体见：https://cmdb-web.ucloudadmin.com/docs/#api-appendix-query-syntax
        type: string
    type: object
info:
  contact: {}
  description: a template
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ProxyHub
  version: "1.0"
paths:
  /api/proxy_group:
    post:
      consumes:
      - application/json
      description: 创建一个新的代理分组
      parameters:
      - description: 创建参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/proxy_group.CreateParams'
      produces:
      - application/json
      responses:
        "200":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                Data:
                  $ref: '#/definitions/models.ProxyGroups'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: 创建分组
      tags:
      - 分组管理
  /api/proxy_group/{id}:
    get:
      consumes:
      - application/json
      description: 获取分组详情
      parameters:
      - description: 分组ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                Data:
                  $ref: '#/definitions/models.ProxyGroups'
              type: object
        "500":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            $ref: '#/definitions/common.Response'
      summary: 获取分组详情
      tags:
      - 分组管理
  /api/proxy_group/delete:
    delete:
      consumes:
      - application/json
      description: 删除分组
      parameters:
      - description: 删除请求参数
        in: body
        name: params
        schema:
          $ref: '#/definitions/proxy_group.DeleteParams'
      produces:
      - application/json
      responses:
        "200":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            $ref: '#/definitions/common.Response'
      summary: 删除分组
      tags:
      - 分组管理
  /api/proxy_group/list:
    post:
      consumes:
      - application/json
      description: 获取分组列表
      parameters:
      - description: 查询通用请求参数
        in: body
        name: params
        schema:
          $ref: '#/definitions/types.BasicQuery'
      produces:
      - application/json
      responses:
        "200":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseWithTotalCount'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/models.ProxyGroups'
                  type: array
              type: object
        "500":
          description: 结果：{RetCode:code,Data:数据,Message:消息}
          schema:
            $ref: '#/definitions/common.Response'
      summary: 获取分组列表
      tags:
      - 分组管理
swagger: "2.0"
